### ISSUE TITLE
sh.exe": dargonStartWyvern: command not found

### ISSUE THREAD

**Issue by rekane88** [the-dargon-project/dargon-developer-scripts#4]
I get this error upon following the wiki guide.

**Comment by miyu** [comment]
Wyvern's our backend and isn't currently complete (or in development). Where on the wiki did you get told to run that?

**Comment by rekane88** [comment]
'Run the command' dargonSetupEnvironment after it does it's thing. It just stops working after that. And when I try to run dargonBuild it just gives me a ton of errors like 

ModificationComponentAttribute.cs(13,37): error CS1002: ; expected [c:\my-repos
itories\the-dargon-project\Dargon.Modifications.Api\Dargon.Modifications.Api.cs
proj]
ModificationComponentAttribute.cs(13,46): error CS1519: Invalid token ';' in cl
ass, struct, or interface member declaration [c:\my-repositories\the-dargon-pro
ject\Dargon.Modifications.Api\Dargon.Modifications.Api.csproj]
ModificationComponentAttribute.cs(14,30): error CS1002: ; expected [c:\my-repos
itories\the-dargon-project\Dargon.Modifications.Api\Dargon.Modifications.Api.cs
proj]
ModificationComponentAttribute.cs(14,41): error CS1519: Invalid token ';' in cl
ass, struct, or interface member declaration [c:\my-repositories\the-dargon-pro
ject\Dargon.Modifications.Api\Dargon.Modifications.Api.csproj]
ThumbnailComponent.cs(37,25): error CS1056: Unexpected character '$' [c:\my-rep
ositories\the-dargon-project\Dargon.Modifications.Api\Dargon.Modifications.Api.
csproj]
ThumbnailComponent.cs(39,25): error CS1056: Unexpected character '$' [c:\my-rep
ositories\the-dargon-project\Dargon.Modifications.Api\Dargon.Modifications.Api.
csproj]
ThumbnailComponent.cs(43,28): error CS1056: Unexpected character '$' [c:\my-rep
ositories\the-dargon-project\Dargon.Modifications.Api\Dargon.Modifications.Api.
csproj]
ThumbnailComponent.cs(45,28): error CS1056: Unexpected character '$' [c:\my-rep
ositories\the-dargon-project\Dargon.Modifications.Api\Dargon.Modifications.Api.
csproj]
ThumbnailComponent.cs(49,31): error CS1056: Unexpected character '$' [c:\my-rep
ositories\the-dargon-project\Dargon.Modifications.Api\Dargon.Modifications.Api.
csproj]
ThumbnailComponent.cs(51,31): error CS1056: Unexpected character '$' [c:\my-rep
ositories\the-dargon-project\Dargon.Modifications.Api\Dargon.Modifications.Api.
csproj]
Components\CommandListComponent.cs(17,38): error CS1002: ; expected [c:\my-repo
sitories\the-dargon-project\Dargon.Trinkets.Api\Dargon.Trinkets.Api.csproj]
Components\CommandListComponent.cs(17,52): error CS1519: Invalid token ';' in c
lass, struct, or interface member declaration [c:\my-repositories\the-dargon-pr
oject\Dargon.Trinkets.Api\Dargon.Trinkets.Api.csproj]
Components\NameComponent.cs(15,27): error CS1002: ; expected [c:\my-repositorie
s\the-dargon-project\Dargon.Trinkets.Api\Dargon.Trinkets.Api.csproj]
Components\NameComponent.cs(15,35): error CS1519: Invalid token ';' in class, s
truct, or interface member declaration [c:\my-repositories\the-dargon-project\D
argon.Trinkets.Api\Dargon.Trinkets.Api.csproj]

**Comment by miyu** [comment]
Are you running vs2015? Our codebase uses some c# 6.0 language features.

**Comment by rekane88** [comment]
I see, I'll have to use VS2015 then. I was using 2013

**Comment by miyu** [comment]
Did you get Dargon building?

**Comment by rekane88** [comment]
Well, where does it output too if it does work?

**Comment by rekane88** [comment]
Severity    Code    Description Project File    Line
Error   C3861   'assert': identifier not found  DargonLibCpp    c:\my-repositories\the-dargon-project-master\dargonlibcpp\src\vfm\vfm_file.cpp  41
Error   C1083   Cannot open include file: 'detours.h': No such file or directory (compiling source file Application.cpp)    Dargon - Injected Module    c:\my-repositories\the-dargon-project-master\dargoninjectedmodule\subsystem.detours.hpp 5
Error   C1083   Cannot open include file: 'detours.h': No such file or directory (compiling source file Commands\FileRemappingCommandHandler.cpp)   Dargon - Injected Module    c:\my-repositories\the-dargon-project-master\dargoninjectedmodule\subsystem.detours.hpp 5
Error   C1083   Cannot open include file: 'detours.h': No such file or directory (compiling source file Commands\FileRedirectionCommandHandler.cpp) Dargon - Injected Module    c:\my-repositories\the-dargon-project-master\dargoninjectedmodule\subsystem.detours.hpp 5
Error   C1083   Cannot open include file: 'detours.h': No such file or directory (compiling source file Subsystems\KernelSubsystem.cpp) Dargon - Injected Module    c:\my-repositories\the-dargon-project-master\dargoninjectedmodule\subsystem.detours.hpp 5
Error   C1083   Cannot open include file: 'detours.h': No such file or directory (compiling source file main.cpp)   Dargon - Injected Module    c:\my-repositories\the-dargon-project-master\dargoninjectedmodule\subsystem.detours.hpp 5
Error   C1083   Cannot open include file: 'detours.h': No such file or directory (compiling source file Subsystems\FileSubsystem.cpp)   Dargon - Injected Module    c:\my-repositories\the-dargon-project-master\dargoninjectedmodule\subsystem.detours.hpp 5
Error   LNK2001 unresolved external symbol "public: __thiscall dargon::countdown_event::countdown_event(unsigned int)" (??0countdown_event@dargon@@QAE@I@Z) DargonLibCpp.Tests  C:\my-repositories\the-dargon-project-master\DargonLibCpp\Tests\ConcurrentDictionaryTests.obj   1
Error   LNK2001 unresolved external symbol "public: void __thiscall dargon::countdown_event::signal(void)" (?signal@countdown_event@dargon@@QAEXXZ) DargonLibCpp.Tests  C:\my-repositories\the-dargon-project-master\DargonLibCpp\Tests\ConcurrentDictionaryTests.obj   1
Error   LNK2001 unresolved external symbol "public: void __thiscall dargon::countdown_event::wait(void)const " (?wait@countdown_event@dargon@@QBEXXZ)   DargonLibCpp.Tests  C:\my-repositories\the-dargon-project-master\DargonLibCpp\Tests\ConcurrentDictionaryTests.obj   1
Error   LNK2001 unresolved external symbol "public: bool __thiscall dargon::countdown_event::wait(unsigned int)const " (?wait@countdown_event@dargon@@QBE_NI@Z) DargonLibCpp.Tests  C:\my-repositories\the-dargon-project-master\DargonLibCpp\Tests\ConcurrentDictionaryTests.obj   1
Error   LNK2019 unresolved external symbol "public: __thiscall dargon::countdown_event::countdown_event(unsigned int)" (??0countdown_event@dargon@@QAE@I@Z) referenced in function "public: void __thiscall dargon::ConcurrentSetTests::MultiThreadedTest(void)" (?MultiThreadedTest@ConcurrentSetTests@dargon@@QAEXXZ) DargonLibCpp.Tests  C:\my-repositories\the-dargon-project-master\DargonLibCpp\Tests\ConcurrentSetTests.obj  1
Error   LNK2019 unresolved external symbol "public: void __thiscall dargon::countdown_event::signal(void)" (?signal@countdown_event@dargon@@QAEXXZ) referenced in function "private: void __thiscall dargon::ConcurrentSetTests::AddRemoveThread(class std::vector<unsigned int,class std::allocator<unsigned int> > &,class dargon::countdown_event const *,class dargon::countdown_event *,class dargon::countdown_event const *,class dargon::countdown_event *,class dargon::countdown_event const *,class dargon::countdown_event const *,class dargon::countdown_event *)" (?AddRemoveThread@ConcurrentSetTests@dargon@@AAEXAAV?$vector@IV?$allocator@I@std@@@std@@PBVcountdown_event@2@PAV52@12112@Z)    DargonLibCpp.Tests  C:\my-repositories\the-dargon-project-master\DargonLibCpp\Tests\ConcurrentSetTests.obj  1
Error   LNK2019 unresolved external symbol "public: void __thiscall dargon::countdown_event::wait(void)const " (?wait@countdown_event@dargon@@QBEXXZ) referenced in function "private: void __thiscall dargon::ConcurrentSetTests::AddRemoveThread(class std::vector<unsigned int,class std::allocator<unsigned int> > &,class dargon::countdown_event const *,class dargon::countdown_event *,class dargon::countdown_event const *,class dargon::countdown_event *,class dargon::countdown_event const *,class dargon::countdown_event const *,class dargon::countdown_event *)" (?AddRemoveThread@ConcurrentSetTests@dargon@@AAEXAAV?$vector@IV?$allocator@I@std@@@std@@PBVcountdown_event@2@PAV52@12112@Z)  DargonLibCpp.Tests  C:\my-repositories\the-dargon-project-master\DargonLibCpp\Tests\ConcurrentSetTests.obj  1
Error   LNK2019 unresolved external symbol "public: bool __thiscall dargon::countdown_event::wait(unsigned int)const " (?wait@countdown_event@dargon@@QBE_NI@Z) referenced in function "private: void __thiscall dargon::ConcurrentSetTests::AddRemoveThread(class std::vector<unsigned int,class std::allocator<unsigned int> > &,class dargon::countdown_event const *,class dargon::countdown_event *,class dargon::countdown_event const *,class dargon::countdown_event *,class dargon::countdown_event const *,class dargon::countdown_event const *,class dargon::countdown_event *)" (?AddRemoveThread@ConcurrentSetTests@dargon@@AAEXAAV?$vector@IV?$allocator@I@std@@@std@@PBVcountdown_event@2@PAV52@12112@Z)    DargonLibCpp.Tests  C:\my-repositories\the-dargon-project-master\DargonLibCpp\Tests\ConcurrentSetTests.obj  1
Error   LNK1120 4 unresolved externals  DargonLibCpp.Tests  C:\my-repositories\the-dargon-project-master\Debug\DargonLibCpp.Tests.dll   1

**Comment by miyu** [comment]
When you run dargonBuild commands, output goes to console. When you run dargonStart commands, then output goes to $DARGON_DIR/logs.

You need microsoft detours setup to build the C++ code at the moment.

**Comment by rekane88** [comment]
So to build the client I need microsoft detours to build the client?

**Comment by rekane88** [comment]
http://www.microsoftstore.com/store/msusa/en_US/pdp/Microsoft-Research-Detours-v3-Professional/productID.253663300?tduid=(3ea03f775ba9af192ff9a0986ebf370e)(256380)(2459594)(1UzQjzPXg9U-7g7Ej_nzfxYEqVdTIVgYdw)() Woah pricey

**Comment by miyu** [comment]
http://research.microsoft.com/en-us/projects/detours/ See: detours express, which is free.

**Comment by rekane88** [comment]
Severity    Code    Description Project File    Line
Error   C3861   'DetourRemove': identifier not found    Dargon - Injected Module    c:\my-repositories\the-dargon-project-master\dargoninjectedmodule\subsystems\filesubsystem.cpp  88
Error   C3861   'DetourFunction': identifier not found  Dargon - Injected Module    c:\my-repositories\the-dargon-project-master\dargoninjectedmodule\subsystems\filesubsystem.cpp  88

**Comment by rekane88** [comment]
That is probably due to you using an older version of detours. Which one were you using?

**Comment by miyu** [comment]
I'd try the previous major version if that's available.

**Comment by miyu** [comment]
Closing due to no response
