### ISSUE TITLE
[help wanted] Nuget 404 not found Errors

### ISSUE THREAD

**Issue by rekane88** [the-dargon-project/dargon-developer-scripts#5]
I get this error upon using the dargonSetupEnvironment command 
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
Unable to find version '0.0.2' of package 'libdargon.hydar-api'.
Unable to find version '0.0.12' of package 'libdpo'.
Unable to find version '0.0.4' of package 'libdsp'.
Unable to find version '0.0.15' of package 'libwarty'.
Unable to find version '0.0.16' of package 'libwarty.proxies-api'.
Dargon.SystemState.Api: Dargon.Platform: Installing 'Castle.Core 3.3.3'.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
WARNING: The remote server returned an error: (404) Not Found.
Successfully installed 'Castle.Core 3.3.3'.
Unable to find version '0.0.13' of package 'libdpo'.
Unable to find version '0.0.0' of package 'Dargon.SystemState.Api'.
Unable to find version '0.0.2' of package 'libdargon.hydar-api'.
Unable to find version '0.0.0' of package 'libdargon.management-api'.
Unable to find version '0.0.15' of package 'libwarty'.
Unable to find version '0.0.1' of package 'libdargon.filesystem-api'.
Unable to find version '0.0.0' of package 'libdargon.filesystem-impl'.
Unable to find version '0.0.0' of package 'libdargon.hydar-local-impl'.
Unable to find version '0.0.0' of package 'libdargon.management-impl'.
Unable to find version '0.0.3' of package 'libdargon.utilities'.
Unable to find version '0.0.12' of package 'libdpo'.
Unable to find version '0.0.4' of package 'libdsp'.
Unable to find version '0.0.16' of package 'libwarty.proxies-api'.
Unable to find version '0.0.12' of package 'libwarty.proxies-impl'.

**Comment by miyu** [comment]
Derp, looks like dSE pulls some projects that are no longer in use. At the moment it's probably best to just pull the-dargon-project and Dargon.Nest and build w/ dargonBuild.

**Comment by rekane88** [comment]
Do I need to modify the .bash file in my user folder

**Comment by rekane88** [comment]
Can't even compile Dragon.Nest get errors like

Error   40  Unexpected character '$'    C:\my-repositories\Dargon.Nest.Exeggutor.Impl\HatchlingContextFactory.cs    34  22  Dargon.Nest.Exeggutor.Impl
Error   41  ; expected  C:\my-repositories\Dargon.Nest.Exeggutor.Impl\ExeggutorServiceImpl.cs   46  55  Dargon.Nest.Exeggutor.Impl
Error   42  Invalid token ';' in class, struct, or interface member declaration C:\my-repositories\Dargon.Nest.Exeggutor.Impl\ExeggutorServiceImpl.cs   46  86  Dargon.Nest.Exeggutor.Impl
Error   43  ; expected  C:\my-repositories\Dargon.Nest.Exeggutor.Impl\HatchlingContext.cs   50  30  Dargon.Nest.Exeggutor.Impl
Error   44  Invalid token ';' in class, struct, or interface member declaration C:\my-repositories\Dargon.Nest.Exeggutor.Impl\HatchlingContext.cs   50  43  Dargon.Nest.Exeggutor.Impl
Error   45  ; expected  C:\my-repositories\Dargon.Nest.Exeggutor.Impl\HatchlingContext.cs   51  26  Dargon.Nest.Exeggutor.Impl
Error   46  Invalid token ';' in class, struct, or interface member declaration C:\my-repositories\Dargon.Nest.Exeggutor.Impl\HatchlingContext.cs   51  33  Dargon.Nest.Exeggutor.Impl
Error   47  ; expected  C:\my-repositories\Dargon.Nest.Exeggutor.Impl\HatchlingContext.cs   52  26  Dargon.Nest.Exeggutor.Impl

**Comment by miyu** [comment]
See other comment on need for vs2015 for c# 6.0 features.
